DROP DATABASE IF EXISTS metroApp;
CREATE DATABASE metroApp;
USE metroApp;
CREATE TABLE Cars (
num VARCHAR(255) UNIQUE NOT NULL,
volume VARCHAR(255) NOT NULL DEFAULT "unchecked",
heavy BOOLEAN NOT NULL DEFAULT 0,
keyz BOOLEAN NOT NULL DEFAULT 0,
flashers BOOLEAN NOT NULL DEFAULT 0,
clear BOOLEAN NOT NULL DEFAULT 0,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
);
CREATE TABLE LatestPuts (
latestPut VARCHAR(255) NOT NULL,
createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
);

INSERT INTO LatestPuts (latestPut) VALUES (0);