DROP DATABASE IF EXISTS metroApp;
CREATE DATABASE metroApp;
USE metroApp;
CREATE TABLE Cars (
num VARCHAR(255) NOT NULL,
keyz BOOLEAN NOT NULL,
flashers BOOLEAN NOT NULL,
clear BOOLEAN NOT NULL,
id int NOT NULL AUTO_INCREMENT,
PRIMARY KEY (id)
);